[FIO internal] core: imx: fix building imx6ulevk
CAAM driver for i.MX6UL is removed from OP-TEE. Now noone provides
the function tee_otp_get_hw_unique_key which is used in huk_subkey.c.
Add an exception to use weak implementation of tee_otp_get_hw_unique_key
for imx6ulevk. It fixes building error [1].

[1]
arm-none-linux-gnueabihf-ld.bfd: out/core/kernel/huk_subkey.o: in function `huk_subkey_derive':
core/kernel/huk_subkey.c:78: undefined reference to `tee_otp_get_hw_unique_key'
make: *** [core/arch/arm/kernel/link.mk:69: out/core/all_objs.o] Error 1

Fixes: 6a1a3dcbf ("[FIO internal] core: imx: remove HUK weak stub implementation")
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>